[package]
name = "bl-rom-rt-macros"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.51"
quote = "1.0.23"

[dependencies.syn]
version = "1.0.107"
features = ["extra-traits", "full"]
